icingahostfilepath: '/tmp/ASG_EC2_Host.conf'
hosttemplatepath: '/tmp/ec2host.j2'
ASG_NAME:
  - 'asdf'
  - 'MoodleCloudASG'
  - 'asdfww'
  - 'Demoasg'
region_name:
  - 'us-east-1'
  - 'us-east-2'
  - 'us-west-2'

Namespace: 'AWS/EC2'
MetricName: 'CPUUtilization'
