icingahostfilepath: '/tmp/ASG_EC2_Host.conf'
hosttemplatepath: '/tmp/ec2host.j2'
region_name:
  - 'us-west-2'
Namespace: 'CWAgent'
MetricName: 'disk_used_percent'
ASG_NAME:
  - 'MoodleCloudASG'
mountpath:
  - '/'
  - '/mydata'

