icingahostfilepath: '/tmp/ASG_EC2_Host.conf'
hosttemplatepath: '/tmp/ec2host.j2'
ASG_NAME:
  - 'MoodleCloudASG'
  - 'ushg'
  - 'Demoasg'
region_name:
  - 'us-west-2'
  - 'us-east-2'
Namespace: 'AWS/EC2'
MetricName: 'CPUUtilization'
